In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/mlss-sp-25/sample_submission.csv
/kaggle/input/mlss-sp-25/train.csv
/kaggle/input/mlss-sp-25/test.csv

In [2]:
train = pd.read_csv("/kaggle/input/mlss-sp-25/train.csv")
test = pd.read_csv("/kaggle/input/mlss-sp-25/test.csv")

In [3]:
import warnings
warnings.filterwarnings("ignore", category = RuntimeWarning)

In [4]:
train

,object_id,transaction_currency,height_cm,width_cm,location,category,date,n_previous_owners,creation_year,is_titled,signed,dated,n_exhibited,artist_birth_year,artist_death_year,estimate,price_realized
0,yzkxu,USD,67.3,55.9,New York,Paintings,2008-01-11,4.0,1996.0,NaN,True,True,0,1937.0,NaN,15000.00,9375.000
1,iponc,USD,122.2,122.2,New York,Paintings,2008-01-11,1.0,NaN,False,True,True,0,1952.0,NaN,2500.00,3750.000
2,ybhua,USD,15.2,10.2,New York,Paintings,2008-01-11,2.0,NaN,True,True,True,2,1958.0,NaN,6000.00,11250.000
3,koiua,USD,58.4,67.3,New York,Paintings,2008-01-11,2.0,NaN,False,True,True,0,1973.0,NaN,5000.00,9375.000
4,wynxu,USD,68.6,52.7,New York,Paintings,2008-01-11,1.0,1957.0,NaN,True,False,0,1917.0,NaN,25000.00,15000.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105896,sznqd,EUR,83.3,65.4,Paris,Paintings,2016-09-14,1.0,NaN,NaN,False,False,5,1864.0,1956.0,19724.25,30995.250
105897,ykbkf,EUR,14.9,26.8,Paris,Paintings,2016-09-14,NaN,NaN,NaN,False,False,0,1816.0,1878.0,5635.50,5353.725
105898,yqcfd,EUR,22.1,17,Paris,Paintings,2016-09-14,NaN,NaN,NaN,False,False,0,1851.0,1929.0,1127.10,1127.100
105899,amurb,EUR,49.9,70.9,Paris,Paintings,2016-09-14,NaN,NaN,NaN,False,False,0,1624.0,1685.0,14088.75,14088.750
105900,uckrb,EUR,18.5,16,Paris,Paintings,2016-09-14,NaN,NaN,NaN,False,False,0,NaN,NaN,28177.50,26768.625

In [5]:
train.isnull().sum()

object_id                   0
transaction_currency        0
height_cm               21700
width_cm                21700
location                 1879
category                    0
date                        0
n_previous_owners       42334
creation_year           75552
is_titled               88123
signed                      0
dated                       0
n_exhibited                 0
artist_birth_year       16253
artist_death_year       32964
estimate                   84
price_realized              0
dtype: int64

In [6]:
train.shape

(105901, 17)

In [7]:
test.isnull().sum()

object_id                   0
transaction_currency        0
height_cm                4173
width_cm                 4173
location                    0
category                    0
date                        0
n_previous_owners        9077
creation_year           27382
is_titled               40819
signed                      0
dated                       0
n_exhibited                 0
artist_birth_year        4967
artist_death_year       16044
estimate                   82
dtype: int64

In [8]:
test.shape

(52951, 16)

In [9]:
train = train.drop(['creation_year', 'is_titled'], axis = 1)
test = test.drop(['creation_year', 'is_titled'], axis = 1)

In [10]:
train.isnull().sum()

object_id                   0
transaction_currency        0
height_cm               21700
width_cm                21700
location                 1879
category                    0
date                        0
n_previous_owners       42334
signed                      0
dated                       0
n_exhibited                 0
artist_birth_year       16253
artist_death_year       32964
estimate                   84
price_realized              0
dtype: int64

In [11]:
def clean_numeric(value):
    try:
        return float(value)
    except:
        return None

train = train.copy()
test = test.copy()

train.loc[:, 'height_cm'] = train['height_cm'].apply(clean_numeric)
train.loc[:, 'width_cm'] = train['width_cm'].apply(clean_numeric)
test.loc[:, 'height_cm'] = test['height_cm'].apply(clean_numeric)
test.loc[:, 'width_cm'] = test['width_cm'].apply(clean_numeric)

In [12]:
from sklearn.impute import SimpleImputer
mean_impute_col = ['height_cm', 'width_cm', 'n_previous_owners', 'estimate']
mean_imputer = SimpleImputer(strategy = "mean")
train[mean_impute_col] = mean_imputer.fit_transform(train[mean_impute_col])
test[mean_impute_col] = mean_imputer.transform(test[mean_impute_col])

In [13]:
from sklearn.impute import SimpleImputer
mode_impute_col = ['location', 'artist_birth_year', 'artist_death_year']
mode_impute = SimpleImputer(strategy = "most_frequent")
train[mode_impute_col] = mode_impute.fit_transform(train[mode_impute_col])
test[mode_impute_col] = mode_impute.transform(test[mode_impute_col])

In [14]:
train.isnull().sum().sum()

0

In [15]:
test.isnull().sum().sum()

0

In [16]:
train

,object_id,transaction_currency,height_cm,width_cm,location,category,date,n_previous_owners,signed,dated,n_exhibited,artist_birth_year,artist_death_year,estimate,price_realized
0,yzkxu,USD,67.3,55.9,New York,Paintings,2008-01-11,4.00000,True,True,0,1937.0,1976.0,15000.00,9375.000
1,iponc,USD,122.2,122.2,New York,Paintings,2008-01-11,1.00000,True,True,0,1952.0,1976.0,2500.00,3750.000
2,ybhua,USD,15.2,10.2,New York,Paintings,2008-01-11,2.00000,True,True,2,1958.0,1976.0,6000.00,11250.000
3,koiua,USD,58.4,67.3,New York,Paintings,2008-01-11,2.00000,True,True,0,1973.0,1976.0,5000.00,9375.000
4,wynxu,USD,68.6,52.7,New York,Paintings,2008-01-11,1.00000,True,False,0,1917.0,1976.0,25000.00,15000.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105896,sznqd,EUR,83.3,65.4,Paris,Paintings,2016-09-14,1.00000,False,False,5,1864.0,1956.0,19724.25,30995.250
105897,ykbkf,EUR,14.9,26.8,Paris,Paintings,2016-09-14,2.25831,False,False,0,1816.0,1878.0,5635.50,5353.725
105898,yqcfd,EUR,22.1,17.0,Paris,Paintings,2016-09-14,2.25831,False,False,0,1851.0,1929.0,1127.10,1127.100
105899,amurb,EUR,49.9,70.9,Paris,Paintings,2016-09-14,2.25831,False,False,0,1624.0,1685.0,14088.75,14088.750
105900,uckrb,EUR,18.5,16.0,Paris,Paintings,2016-09-14,2.25831,False,False,0,1928.0,1976.0,28177.50,26768.625

In [17]:
ID = test['object_id']
train = train.drop('object_id', axis = 1)
test = test.drop('object_id', axis = 1)

In [18]:
train

,transaction_currency,height_cm,width_cm,location,category,date,n_previous_owners,signed,dated,n_exhibited,artist_birth_year,artist_death_year,estimate,price_realized
0,USD,67.3,55.9,New York,Paintings,2008-01-11,4.00000,True,True,0,1937.0,1976.0,15000.00,9375.000
1,USD,122.2,122.2,New York,Paintings,2008-01-11,1.00000,True,True,0,1952.0,1976.0,2500.00,3750.000
2,USD,15.2,10.2,New York,Paintings,2008-01-11,2.00000,True,True,2,1958.0,1976.0,6000.00,11250.000
3,USD,58.4,67.3,New York,Paintings,2008-01-11,2.00000,True,True,0,1973.0,1976.0,5000.00,9375.000
4,USD,68.6,52.7,New York,Paintings,2008-01-11,1.00000,True,False,0,1917.0,1976.0,25000.00,15000.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105896,EUR,83.3,65.4,Paris,Paintings,2016-09-14,1.00000,False,False,5,1864.0,1956.0,19724.25,30995.250
105897,EUR,14.9,26.8,Paris,Paintings,2016-09-14,2.25831,False,False,0,1816.0,1878.0,5635.50,5353.725
105898,EUR,22.1,17.0,Paris,Paintings,2016-09-14,2.25831,False,False,0,1851.0,1929.0,1127.10,1127.100
105899,EUR,49.9,70.9,Paris,Paintings,2016-09-14,2.25831,False,False,0,1624.0,1685.0,14088.75,14088.750
105900,EUR,18.5,16.0,Paris,Paintings,2016-09-14,2.25831,False,False,0,1928.0,1976.0,28177.50,26768.625

In [19]:
cat = ['transaction_currency', 'location', 'category', 'signed', 'dated']
train_dummies = pd.get_dummies(train[cat], drop_first = True).astype(int)
test_dummies = pd.get_dummies(test[cat], drop_first = True).astype(int)

In [20]:
test_dummies = test_dummies.reindex(columns = train_dummies.columns, fill_value = 0)

In [21]:
train = pd.concat([train.drop(cat, axis = 1), train_dummies], axis = 1)
test = pd.concat([test.drop(cat, axis = 1), test_dummies], axis = 1)

In [22]:
X_train = train.drop(['price_realized','date'], axis = 1)
test = test.drop(['date'], axis = 1)
y_train = train['price_realized']

In [23]:
from sklearn.linear_model import Ridge, Lasso
from sklearn.model_selection import cross_val_score, GridSearchCV, KFold
from sklearn.metrics import make_scorer, mean_absolute_percentage_error
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [24]:
kf = KFold(n_splits=5, shuffle=True, random_state=42)

In [25]:
mape_scorer = make_scorer(mean_absolute_percentage_error, greater_is_better=False)

In [26]:
# Ridge Regression with cross-validation
ridge = Ridge()
ridge_params = {'alpha': np.logspace(-3, 3, 50)}
ridge_cv = GridSearchCV(ridge, ridge_params, scoring=mape_scorer, cv=kf, return_train_score=True)
ridge_cv.fit(X_train, y_train)

best_ridge_alpha = ridge_cv.best_params_['alpha']
best_ridge_score = -ridge_cv.best_score_
best_ridge_model = ridge_cv.best_estimator_

print(f"Best Ridge Alpha: {best_ridge_alpha}, Best Ridge MAPE: {best_ridge_score}, Best Ridge Model: {best_ridge_model}")

Best Ridge Alpha: 1000.0, Best Ridge MAPE: 6.136571987629682, Best Ridge Model: Ridge(alpha=1000.0)

In [27]:
# Lasso Regression with cross-validation
lasso = Lasso(max_iter=10000)
lasso_params = {'alpha': np.logspace(-3, 3, 25)}
lasso_cv = GridSearchCV(lasso, lasso_params, scoring=mape_scorer, cv=kf, return_train_score=True)
lasso_cv.fit(X_train, y_train)

best_lasso_alpha = lasso_cv.best_params_['alpha']
best_lasso_score = -lasso_cv.best_score_
best_lasso_model = ridge_cv.best_estimator_

print(f"Best Lasso Alpha: {best_lasso_alpha}, Best Lasso MAPE: {best_lasso_score}, Best Lasso Model: {best_lasso_model}")

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.821e+15, tolerance: 2.129e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.975e+15, tolerance: 1.842e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.990e+15, tolerance: 2.124e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.772e+15, tolerance: 2.042e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.168e+15, tolerance: 2.100e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.821e+15, tolerance: 2.129e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.975e+15, tolerance: 1.842e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.990e+15, tolerance: 2.124e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.772e+15, tolerance: 2.042e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.168e+15, tolerance: 2.100e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.821e+15, tolerance: 2.129e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.975e+15, tolerance: 1.842e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.990e+15, tolerance: 2.124e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.772e+15, tolerance: 2.042e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.168e+15, tolerance: 2.100e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.821e+15, tolerance: 2.129e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.975e+15, tolerance: 1.842e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.990e+15, tolerance: 2.124e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.772e+15, tolerance: 2.042e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.168e+15, tolerance: 2.100e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.821e+15, tolerance: 2.129e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.975e+15, tolerance: 1.842e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.990e+15, tolerance: 2.124e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.772e+15, tolerance: 2.042e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.168e+15, tolerance: 2.100e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.685e+15, tolerance: 2.129e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.975e+15, tolerance: 1.842e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.499e+13, tolerance: 2.124e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.153e+15, tolerance: 2.100e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.835e+15, tolerance: 1.842e+13
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.835e+15, tolerance: 1.842e+13
  model = cd_fast.enet_coordinate_descent(

Best Lasso Alpha: 1000.0, Best Lasso MAPE: 5.658590752364744, Best Lasso Model: Ridge(alpha=1000.0)

In [28]:
print(f"Best Lasso Alpha: {best_lasso_alpha}, Best Lasso MAPE: {best_lasso_score}, Best Lasso Model: {best_lasso_model}")

Best Lasso Alpha: 1000.0, Best Lasso MAPE: 5.658590752364744, Best Lasso Model: Ridge(alpha=1000.0)

In [29]:
# Train final Lasso model with best alpha
lasso_final = Lasso(alpha=best_lasso_alpha)
lasso_final.fit(X_train, y_train)

Lasso(alpha=1000.0)

In [30]:
# Identify features eliminated by LASSO
lasso_coefficients = pd.Series(lasso_final.coef_, index = X_train.columns)
eliminated_features = lasso_coefficients[lasso_coefficients == 0].index.tolist()

In [31]:
# Compare Ridge and LASSO, select the best model
if best_ridge_score < best_lasso_score:
    final_model = Ridge(alpha=best_ridge_alpha)
    final_model.fit(X_train, y)
    test_predictions = final_model.predict(test)
    chosen_model = "Ridge"
    best_score = best_ridge_score
else:
    final_model = lasso_final
    test_predictions = final_model.predict(test)
    chosen_model = "LASSO"
    best_score = best_lasso_score

In [32]:
sample = test = pd.read_csv("/kaggle/input/mlss-sp-25/sample_submission.csv")
sample

      object_id  price_realized
0         gnite      67887.1425
1         agxtc       3655.0700
2         otrwd      43267.3000
3         yqyhe      39582.9200
4         cpqne       2750.6000
...         ...             ...
52946     yhuiq      35266.0000
52947     kwujo     166352.0000
52948     wyapo      43737.1000
52949     ebiyn       8948.5000
52950     sogyn      19669.4310

[52951 rows x 2 columns]

In [33]:
# Save predictions
submission = pd.DataFrame({'object_id': ID, 'price_realized': test_predictions})
submission.to_csv("submission.csv", index=False)

In [34]:
submission

      object_id  price_realized
0         gnite     8633.881159
1         agxtc    88966.198301
2         otrwd   -14917.325245
3         yqyhe    18027.837041
4         cpqne    50304.175417
...         ...             ...
52946     yhuiq    26384.713010
52947     kwujo   305230.389417
52948     wyapo     1633.811379
52949     ebiyn    -5451.422713
52950     sogyn   -11870.023498

[52951 rows x 2 columns]